// ELIF OS — interactive calendar layer
(() => {
  const KEY='elif-os-v2-state';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const pad=n=>String(n).padStart(2,'0');
  const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const parse=k=>{const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)};
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const today=()=>key(new Date());
  let viewKey=today();
  const active=x=>String(x?.status||'active').toLowerCase()!=='on hold'&&x?.active!==false;
  const items=s=>[...(s.tasks||[]).filter(t=>active(t)).map(t=>({id:t.id,type:'task',title:t.title,date:t.date,done:t.done,priority:t.priority,projectId:t.projectId,goalId:t.goalId})),...(s.calendarEvents||[]).filter(e=>active(e)).map(e=>({...e,type:'event'}))];
  const monthCells=()=>{const d=parse(viewKey),first=new Date(d.getFullYear(),d.getMonth(),1),start=(first.getDay()+6)%7,count=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();let a=[];for(let i=0;i<start;i++)a.push(null);for(let n=1;n<=count;n++)a.push(new Date(d.getFullYear(),d.getMonth(),n));while(a.length%7)a.push(null);return a};
  const monthName=()=>new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(parse(viewKey));
  const mountNav=()=>{const nav=document.querySelector('nav');if(!nav||nav.querySelector('[data-page="calendar"]'))return;const b=document.createElement('button');b.dataset.page='calendar';b.innerHTML='▦<span>Calendar</span>';const journal=nav.querySelector('[data-page="journal"]');journal?journal.insertAdjacentElement('beforebegin',b):nav.appendChild(b)};
  const openAdd=(date)=>{const modal=document.querySelector('#modal');modal.innerHTML=`<div class="modal-box"><button class="close" data-cal-close>×</button><span class="eyebrow">ELIF OS · CALENDAR</span><h2>New event</h2><form data-cal-form><label>Title<input name="title" required placeholder="e.g. Pharmacy lecture"></label><label>Date<input name="date" type="date" value="${date}"></label><label>Start time<input name="start" type="time" value="09:00"></label><label>End time<input name="end" type="time" value="10:00"></label><label>Type<select name="kind"><option>study</option><option>personal</option><option>workout</option><option>appointment</option><option>deadline</option><option>other</option></select></label><label>Notes<textarea name="notes" placeholder="details..."></textarea></label><button class="primary">save event</button></form>`;modal.classList.add('open')};
  const render=()=>{mountNav();const root=document.querySelector('#view');if(!root)return;const s=read(),d=parse(viewKey),cells=monthCells(),all=items(s);root.innerHTML=`<section><div class="head"><div><span class="eyebrow">ELIF OS · TIME</span><h1>CALENDAR</h1><p>Your tasks and events share one timeline.</p></div><button class="primary" data-cal-add="${today()}">＋ event</button></div><div class="calendar-toolbar"><button data-cal-prev>‹</button><button data-cal-today>Today</button><strong>${esc(monthName())}</strong><button data-cal-next>›</button></div><div class="calendar-grid"><div class="weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span>${x}</span>`).join('')}</div><div class="days">${cells.map(day=>{if(!day)return '<div class="day empty"></div>';const k=key(day),its=all.filter(x=>x.date===k),sel=k===viewKey,isToday=k===today();return `<button class="day ${sel?'selected ':''}${isToday?'today':''}" data-cal-day="${k}"><b>${day.getDate()}</b><div>${its.slice(0,3).map(x=>`<span class="cal-item ${x.type} ${x.done?'done':''}">${x.type==='task'?'✓':'•'} ${esc(x.title)}</span>`).join('')}${its.length>3?`<small>+${its.length-3} more</small>`:''}</div></button>`}).join('')}</div></div><div class="calendar-bottom"><div class="panel"><div class="panel-title"><span>${new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(d)}</span><button data-cal-add="${viewKey}">＋ add</button></div><div class="list">${all.filter(x=>x.date===viewKey).map(x=>`<div class="row"><input type="checkbox" ${x.type==='task'&&x.done?'checked':''} ${x.type!=='task'?'disabled':''} data-cal-task="${x.id}"><div><b>${esc(x.title)}</b><small>${x.type.toUpperCase()}${x.start?` · ${x.start}${x.end?`–${x.end}`:''}`:''}${x.priority?` · ${x.priority}`:''}</small></div>${x.type==='event'?`<button data-cal-delete="${x.id}">×</button>`:''}</div>`).join('')||'<p class="muted">Nothing scheduled. Add an event or task.</p>'}</div></div><div class="panel"><div class="panel-title"><span>UPCOMING</span><span>${all.filter(x=>x.date>=today()).length} items</span></div><div class="list">${all.filter(x=>x.date>=today()).sort((a,b)=>a.date.localeCompare(b.date)||(a.start||'').localeCompare(b.start||'')).slice(0,8).map(x=>`<button class="row" data-cal-day="${x.date}"><div><b>${esc(x.title)}</b><small>${x.date}${x.start?` · ${x.start}`:''}</small></div><span>${x.type}</span></button>`).join('')||'<p class="muted">No upcoming items.</p>'}</div></div></div></section>`};
  const rerender=()=>{render();document.querySelector('#crumb').textContent='Calendar'};
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-page="calendar"]')){e.preventDefault();e.stopImmediatePropagation();viewKey=today();rerender();return}if(b.matches('[data-cal-prev]')){const d=parse(viewKey);viewKey=key(new Date(d.getFullYear(),d.getMonth()-1,1));rerender();return}if(b.matches('[data-cal-next]')){const d=parse(viewKey);viewKey=key(new Date(d.getFullYear(),d.getMonth()+1,1));rerender();return}if(b.matches('[data-cal-today]')){viewKey=today();rerender();return}if(b.matches('[data-cal-day]')){viewKey=b.dataset.calDay;if(b.classList.contains('row'))rerender();else render();return}if(b.matches('[data-cal-add]')){openAdd(b.dataset.calAdd);return}if(b.matches('[data-cal-close]')){document.querySelector('#modal').classList.remove('open');return}if(b.matches('[data-cal-delete]')){const s=read();s.calendarEvents=(s.calendarEvents||[]).filter(x=>x.id!==b.dataset.calDelete);write(s);rerender();return}},true);
  document.addEventListener('submit',e=>{const f=e.target.closest('[data-cal-form]');if(!f)return;e.preventDefault();e.stopImmediatePropagation();const d=new FormData(f),s=read();s.calendarEvents||=[];s.calendarEvents.push({id:crypto.randomUUID(),title:String(d.get('title')),date:String(d.get('date')||today()),start:String(d.get('start')||''),end:String(d.get('end')||''),kind:String(d.get('kind')||'other'),notes:String(d.get('notes')||''),status:'active'});write(s);document.querySelector('#modal').classList.remove('open');viewKey=String(d.get('date')||today());rerender()},true);
  document.addEventListener('change',e=>{const x=e.target.closest('[data-cal-task]');if(!x)return;const s=read(),t=(s.tasks||[]).find(t=>t.id===x.dataset.calTask);if(t){t.done=x.checked;write(s);rerender()}});
  window.ELIFCalendar={render,rerender};
  new MutationObserver(mountNav).observe(document.body,{childList:true,subtree:true});
  setTimeout(()=>{mountNav();if(document.querySelector('#view')&&document.querySelector('#crumb')?.textContent==='Calendar')render()},300);
})();
