// ELIF OS execution command center
(()=>{
const K='elif-os-v2-state',R=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return {}}},W=s=>localStorage.setItem(K,JSON.stringify(s)),T=()=>new Date().toISOString().slice(0,10),A=x=>String(x?.status||'active').toLowerCase()!=='on hold'&&x?.active!==false,E=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])),Q=()=>document.querySelector('#view'),M=(h,b)=>{let m=document.querySelector('#modal');m.innerHTML=`<div class="modal-box"><button class="close" data-ex-close>×</button><span class="eyebrow">ELIF OS · EXECUTION</span><h2>${h}</h2>${b}</div>`;m.classList.add('open')};
let pf='all',gf='all',openProject=null;
function stats(s,p){let t=s.tasks.filter(x=>x.projectId===p.id&&A(x));return [t,t.length?Math.round(t.filter(x=>x.done).length/t.length*100):0]}
function tasks(){let s=R(),t=(s.tasks||[]).filter(A);if(pf!=='all')t=t.filter(x=>x.priority===pf);Q().innerHTML=`<section><div class="head"><div><span class="eyebrow">ELIF OS · EXECUTION</span><h1>TASKS</h1><p>Concrete actions drive project progress.</p></div><button class="primary" data-add-task>＋ task</button></div><div class="toolbar"><select data-ex-filter><option value="all">All priorities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div><div class="list">${t.sort((a,b)=>(a.done?1:0)-(b.done?1:0)||String(a.date).localeCompare(String(b.date))).map(x=>{let p=(s.projects||[]).find(p=>p.id===x.projectId),g=(s.goals||[]).find(g=>g.id===x.goalId);return `<div class="row ${x.done?'done':''}"><input type="checkbox" data-ex-task="${x.id}" ${x.done?'checked':''}><div><b>${E(x.title)}</b><small>${x.date||'No date'} · ${x.priority||'medium'}${p?' · '+E(p.name):''}${g?' · '+E(g.title):''}</small></div><button data-ex-edit="${x.id}">edit</button></div>`}).join('')||'<p class="muted">No active tasks.</p>'}</div></section>`}
function projects(){let s=R(),p=(s.projects||[]).filter(A).filter(x=>gf==='all'||x.goalId===gf);Q().innerHTML=`<section><div class="head"><div><span class="eyebrow">ELIF OS · EXECUTION</span><h1>PROJECTS</h1><p>Projects turn goals into executable work.</p></div><button class="primary" data-add-project>＋ project</button></div><div class="toolbar"><select data-ex-goal><option value="all">All goals</option>${(s.goals||[]).filter(A).map(g=>`<option value="${g.id}" ${gf===g.id?'selected':''}>${E(g.title)}</option>`).join('')}</select></div><div class="cards">${p.map(x=>{let [t,n]=stats(s,x),g=(s.goals||[]).find(g=>g.id===x.goalId);return `<div class="panel"><span class="eyebrow">${E(x.area||'PROJECT')}</span><h3>${E(x.name)}</h3><small>${g?'Goal · '+E(g.title):'No goal linked'}</small><div class="goal-line"><b>${n}%</b><span>${t.filter(x=>x.done).length}/${t.length} tasks</span></div><div class="progress"><i style="width:${n}%"></i></div><div class="quick"><button data-ex-open="${x.id}">open</button><button data-add-task-project="${x.id}">＋ task</button></div></div>`}).join('')||'<p class="muted">No active projects.</p>'}</div></section>`}
function project(id){let s=R(),p=(s.projects||[]).find(x=>x.id===id);if(!p)return projects();let [t,n]=stats(s,p);Q().innerHTML=`<section><div class="head"><div><span class="eyebrow">PROJECT · ${E(p.area||'')}</span><h1>${E(p.name)}</h1><p>${(s.goals||[]).find(g=>g.id===p.goalId)?'Linked to a goal.':'No goal linked.'}</p></div><button class="primary" data-add-task-project="${p.id}">＋ task</button></div><div class="metrics"><div class="metric"><span>Progress</span><strong>${n}%</strong><small>${t.filter(x=>x.done).length}/${t.length} active tasks complete</small><div class="progress"><i style="width:${n}%"></i></div></div></div><div class="panel"><div class="panel-title">Execution queue <button data-ex-back>← projects</button></div><div class="list">${t.map(x=>`<div class="row ${x.done?'done':''}"><input type="checkbox" data-ex-task="${x.id}" ${x.done?'checked':''}><div><b>${E(x.title)}</b><small>${x.date||'No date'} · ${x.priority||'medium'}</small></div><button data-ex-edit="${x.id}">edit</button></div>`).join('')||'<p class="muted">No tasks yet.</p>'}</div></div></section>`}
function goals(){let s=R(),g=(s.goals||[]).filter(A),p=(s.projects||[]).filter(A);Q().innerHTML=`<section><div class="head"><div><span class="eyebrow">ELIF OS · OUTCOMES</span><h1>GOALS</h1><p>Outcome progress is derived from executing projects.</p></div><button class="primary" data-add-goal>＋ goal</button></div><div class="cards">${g.map(x=>{let ps=p.filter(y=>y.goalId===x.id),ep=ps.filter(y=>s.tasks.some(t=>t.projectId===y.id&&A(t))),n=ep.length?Math.round(ep.reduce((a,y)=>a+stats(s,y)[1],0)/ep.length):Number(x.progress||0);return `<div class="panel"><span class="eyebrow">${E(x.area||'AREA')}</span><h3>${E(x.title)}</h3><div class="goal-line"><b>${n}%</b><span>${ep.length} execution projects</span></div><div class="progress"><i style="width:${n}%"></i></div><div class="list">${ps.map(y=>`<button class="row" data-ex-open="${y.id}"><div><b>${E(y.name)}</b><small>${stats(s,y)[1]}% project progress</small></div><span>›</span></button>`).join('')||'<p class="muted">No projects linked.</p>'}</div></div>`}).join('')}</div></section>`}
function edit(id){let s=R(),t=s.tasks.find(x=>x.id===id);if(!t)return;M('Edit task',`<form data-ex-edit-form="${id}"><label>Task<input name="title" value="${E(t.title)}" required></label><label>Date<input name="date" type="date" value="${t.date||T()}"></label><label>Priority<select name="priority">${['low','medium','high'].map(x=>`<option ${t.priority===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Project<select name="projectId"><option value="">No project</option>${(s.projects||[]).filter(A).map(p=>`<option value="${p.id}" ${t.projectId===p.id?'selected':''}>${E(p.name)}</option>`).join('')}</select></label><label>Goal<select name="goalId"><option value="">No goal</option>${(s.goals||[]).filter(A).map(g=>`<option value="${g.id}" ${t.goalId===g.id?'selected':''}>${E(g.title)}</option>`).join('')}</select></label><button class="primary">save changes</button></form>`)}
function current(){let c=document.querySelector('#crumb')?.textContent||'';if(/^Tasks$/i.test(c))tasks();else if(/^Projects$/i.test(c))openProject?project(openProject):projects();else if(/^Goals$/i.test(c))goals()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.matches('[data-ex-open]')){e.preventDefault();e.stopImmediatePropagation();openProject=b.dataset.exOpen;project(openProject)}else if(b.matches('[data-ex-back]')){openProject=null;projects()}else if(b.matches('[data-ex-edit]')){e.preventDefault();e.stopImmediatePropagation();edit(b.dataset.exEdit)}else if(b.matches('[data-ex-close]')){document.querySelector('#modal').classList.remove('open')}},true);
document.addEventListener('change',e=>{let x=e.target.closest('[data-ex-task]');if(x){let s=R(),t=s.tasks.find(t=>t.id===x.dataset.exTask);if(t){t.done=x.checked;W(s);current()}}let f=e.target.closest('[data-ex-filter]');if(f){pf=f.value;tasks()}let g=e.target.closest('[data-ex-goal]');if(g){gf=g.value;projects()}});
document.addEventListener('submit',e=>{let f=e.target.closest('[data-ex-edit-form]');if(!f)return;e.preventDefault();e.stopImmediatePropagation();let s=R(),t=s.tasks.find(x=>x.id===f.dataset.exEditForm),d=new FormData(f);if(t){t.title=d.get('title');t.date=d.get('date');t.priority=d.get('priority');t.projectId=d.get('projectId')||null;t.goalId=d.get('goalId')||null;W(s)}document.querySelector('#modal').classList.remove('open');current()},true);
window.ELIFExecution={tasks,projects,goals,project};setTimeout(current,500);
})();