(()=>{
'use strict';
const root=()=>document.querySelector('#view');
const day=()=>new Date().toISOString().slice(0,10);
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const shell=(title,sub,html)=>`<section><div class="viewhead"><div><h1>${title}</h1><p>${sub}</p></div></div>${html}</section>`;
let timerId=null,remaining=1500,timerMode='focus';
const timerText=()=>String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');
function render(p){const r=root();if(!r)return;r.dataset.page=p;const f=pages[p];if(!f)return;r.innerHTML=f();bind(p)}
function journal(){const s=read('elif-os-journal-v3',{entries:[]});return shell('Journal','Write, reflect, and keep your thoughts private.',`<div class="enh-grid"><div class="panel enh-card"><span class="tag">NEW ENTRY</span><h3>Write it out</h3><input class="enh-input" id="jdate" type="date" value="${day()}"><select class="enh-select" id="jmood"><option>Calm</option><option>Happy</option><option>Focused</option><option>Excited</option><option>Neutral</option><option>Low</option></select><input class="enh-input" id="jtitle" placeholder="Title"><textarea class="enh-textarea journal-area" id="jbody" placeholder="Write freely..."></textarea><div class="enh-row"><button class="primary" id="jsave">save entry</button><button class="ghost" id="jprompt">give me a prompt</button></div><p id="jpromptbox">Click for a writing prompt.</p></div><div class="panel enh-card"><span class="tag">RECENT</span><h3>Your thoughts</h3>${s.entries.slice(0,10).map((x,i)=>`<article class="journal-entry"><b>${esc(x.title)}</b><small>${esc(x.date)} · ${esc(x.mood)}</small><p>${esc(x.body).replace(/\n/g,'<br>')}</p><button class="ghost" data-jdel="${i}">delete</button></article>`).join('')||'<div class="empty-state">Your journal is empty.</div>'}</div></div>`)}
function study(){return shell('Study','Focus timer with short and long breaks.',`<div class="panel enh-card" style="text-align:center"><span class="tag" id="pmode">${timerMode.toUpperCase()}</span><div id="ptime" style="font:clamp(64px,12vw,104px) DM Mono,monospace;margin:12px 0">${timerText()}</div><div class="enh-row" style="justify-content:center"><button class="ghost" data-pmode="focus">25 min focus</button><button class="ghost" data-pmode="short">5 min break</button><button class="ghost" data-pmode="long">15 min break</button></div><div class="enh-row" style="justify-content:center;margin-top:18px"><button class="primary" id="ptoggle">start</button><button class="ghost" id="preset">reset</button></div></div>`)}
function meal(){const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});return shell('Meal','Plan meals, track pantry, and build a shopping list.',`<div class="enh-grid"><div class="panel enh-card"><h3>Meal planner</h3><input class="enh-input" id="mdate" type="date" value="${day()}"><select class="enh-select" id="mtype"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select><input class="enh-input" id="mmeal" placeholder="Meal idea"><button class="primary" id="madd">add to plan</button>${s.plans.map((x,i)=>`<div class="check"><span class="grow"><b>${esc(x.date)}</b> · ${esc(x.type)}<br>${esc(x.meal)}</span><button class="ghost" data-mdel="${i}">×</button></div>`).join('')}</div><div class="panel enh-card"><h3>Pantry</h3><div class="enh-row"><input class="enh-input" id="pitem" placeholder="Ingredient"><input class="enh-input" id="pqty" placeholder="Qty"><button class="primary" id="padd">add</button></div>${s.pantry.map((x,i)=>`<div class="check"><span class="grow">${esc(x.item)} · ${esc(x.qty)}</span><button class="ghost" data-pdel="${i}">×</button></div>`).join('')}</div></div><div class="panel enh-card" style="margin-top:14px"><h3>Shopping list</h3><div class="enh-row"><input class="enh-input" id="sitem" placeholder="Item"><button class="primary" id="sadd">add</button></div>${s.shopping.map((x,i)=>`<label class="check"><input type="checkbox" data-sdone="${i}" ${x.done?'checked':''}><span class="grow">${esc(x.item)}</span><button class="ghost" data-sdel="${i}">×</button></label>`).join('')}</div>`)}
function glow(){const s=read('elif-os-glow-v2',{days:{}}),d=s.days[day()]||{},items=['Morning cleanse','Moisturizer','SPF','Evening cleanse','Serum / treatment','Night moisturizer','Shower','Body moisturizer','Oral care','Hair care','Water 2L','Balanced meals','7–9h sleep'];return shell('Glow Up','Daily skincare, grooming, recovery, and lifestyle.',`<div class="panel enh-card"><h3>Today</h3>${items.map((x,i)=>`<label class="check"><input type="checkbox" data-g="${i}" ${d[i]?'checked':''}><span class="grow">${x}</span></label>`).join('')}<textarea class="enh-textarea" id="gnote" placeholder="Glow note...">${esc(d.note||'')}</textarea><button class="primary" id="gsave">save</button></div>`)}
function wallet(){const s=read('elif-os-wallet-v2',{trades:[]}),pl=s.trades.reduce((a,x)=>a+Number(x.pl||0),0),wins=s.trades.filter(x=>Number(x.pl)>0).length;return shell('Wallet','Trading journal and daily P/L.',`<div class="panel enh-card"><div class="enh-grid three"><div><span class="tag">NET P/L</span><h2>₺${pl.toLocaleString('tr-TR')}</h2></div><div><span class="tag">TRADES</span><h2>${s.trades.length}</h2></div><div><span class="tag">WIN RATE</span><h2>${s.trades.length?Math.round(wins/s.trades.length*100):0}%</h2></div></div><div class="enh-grid"><input class="enh-input" id="wa" placeholder="Asset"><input class="enh-input" id="wpl" type="number" step="0.01" placeholder="P/L ₺"><input class="enh-input" id="wsetup" placeholder="Setup"><input class="enh-input" id="wlesson" placeholder="Lesson"></div><button class="primary" id="wadd">save trade</button>${s.trades.slice(0,10).map((x,i)=>`<div class="check"><span class="grow"><b>${esc(x.asset)}</b> · ₺${Number(x.pl).toLocaleString('tr-TR')}<br><small>${esc(x.setup)} — ${esc(x.lesson)}</small></span><button class="ghost" data-wdel="${i}">×</button></div>`).join('')}</div>`)}
function habits(){const s=read('elif-os-habits-v2',{items:['Study','Movement','Water','Sleep','Read','Korean'],log:{}}),d=s.log[day()]||{};return shell('Habits','Small promises that compound.',`<div class="panel enh-card">${s.items.map((x,i)=>`<label class="check"><input type="checkbox" data-h="${i}" ${d[i]?'checked':''}><span class="grow">${esc(x)}</span></label>`).join('')}</div>`)}
function body(){const s=read('elif-os-body-v1',{days:{}}),d=s.days[day()]||{};return shell('Body','Track movement, weight, recovery, and hydration.',`<div class="panel enh-card"><div class="enh-grid"><input class="enh-input" id="bw" type="number" step="0.1" placeholder="Weight kg" value="${d.weight||''}"><input class="enh-input" id="bm" type="number" placeholder="Workout min" value="${d.workout||''}"><input class="enh-input" id="bs" type="number" step="0.1" placeholder="Sleep h" value="${d.sleep||''}"><input class="enh-input" id="bwa" type="number" step="0.1" placeholder="Water L" value="${d.water||''}"></div><button class="primary" id="bsave">save today's data</button></div>`)}
function goals(){const s=read('elif-os-goals-v2',{items:[]});return shell('Goals','Turn intentions into measurable progress.',`<div class="panel enh-card"><div class="enh-row"><input class="enh-input" id="gt" placeholder="Goal"><input class="enh-input" id="ga" placeholder="Area"><button class="primary" id="gadd">add</button></div>${s.items.map((x,i)=>`<div class="journal-entry"><b>${esc(x.title)}</b> · ${esc(x.area)}<input type="range" min="0" max="100" value="${x.progress}" data-gp="${i}"><span>${x.progress}%</span><button class="ghost" data-gdel="${i}">delete</button></div>`).join('')}</div>`)}
function projects(){const s=read('elif-os-projects-v2',{items:[]});return shell('Projects','Give important work a clear home.',`<div class="panel enh-card"><div class="enh-row"><input class="enh-input" id="pt" placeholder="Project"><input class="enh-input" id="pa" placeholder="Area"><button class="primary" id="paddproj">add</button></div>${s.items.map((x,i)=>`<div class="check"><span class="grow"><b>${esc(x.name)}</b><br><small>${esc(x.area)}</small></span><button class="ghost" data-pdelproj="${i}">×</button></div>`).join('')}</div>`)}
function calendar(){const s=read('elif-os-calendar-v2',{events:[]});return shell('Calendar','Monthly planning with usable day numbers.',`<div class="panel enh-card"><div class="enh-row"><button class="ghost" id="cprev">←</button><h2 class="grow" id="cmonth" style="text-align:center"></h2><button class="ghost" id="cnext">→</button></div><div class="mini calbig" id="calgrid"></div><div class="enh-row"><input class="enh-input" id="cevent" placeholder="Event"><input class="enh-input" id="cedate" type="date" value="${day()}"><button class="primary" id="cadd">add event</button></div><div id="events"></div></div>`)}
const pages={journal,study,meal,glow,wallet,habits,body,goals,projects,calendar};
function bind(p){const v=root();
if(p==='journal'){v.querySelector('#jprompt').onclick=()=>{const q=['What made today better?','What are you avoiding and why?','What would make tomorrow great?','What did you learn today?'][Math.floor(Math.random()*4)];v.querySelector('#jpromptbox').textContent=q;v.querySelector('#jbody').value+=`\n\n${q}\n\n`;v.querySelector('#jbody').focus()};v.querySelector('#jsave').onclick=()=>{const s=read('elif-os-journal-v3',{entries:[]}),title=v.querySelector('#jtitle').value.trim(),body=v.querySelector('#jbody').value.trim();if(!title||!body){alert('Başlık ve metin gerekli.');return}s.entries.unshift({title,body,date:v.querySelector('#jdate').value,mood:v.querySelector('#jmood').value});write('elif-os-journal-v3',s);render(p)};v.querySelectorAll('[data-jdel]').forEach(b=>b.onclick=()=>{const s=read('elif-os-journal-v3',{entries:[]});s.entries.splice(+b.dataset.jdel,1);write('elif-os-journal-v3',s);render(p)})}
if(p==='study'){v.querySelector('#ptoggle').onclick=()=>{const b=v.querySelector('#ptoggle');if(timerId){clearInterval(timerId);timerId=null;b.textContent='start';return}b.textContent='pause';timerId=setInterval(()=>{remaining--;v.querySelector('#ptime').textContent=timerText();if(remaining<=0){clearInterval(timerId);timerId=null;b.textContent='start';alert(`${timerMode} timer finished`)}},1000)};v.querySelector('#preset').onclick=()=>{if(timerId)clearInterval(timerId);timerId=null;remaining=timerMode==='focus'?1500:timerMode==='short'?300:900;v.querySelector('#ptime').textContent=timerText();v.querySelector('#ptoggle').textContent='start'};v.querySelectorAll('[data-pmode]').forEach(b=>b.onclick=()=>{timerMode=b.dataset.pmode;remaining=timerMode==='focus'?1500:timerMode==='short'?300:900;v.querySelector('#pmode').textContent=timerMode.toUpperCase();v.querySelector('#ptime').textContent=timerText()})}
if(p==='meal'){v.querySelector('#madd').onclick=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});s.plans.push({date:v.querySelector('#mdate').value,type:v.querySelector('#mtype').value,meal:v.querySelector('#mmeal').value.trim()});write('elif-os-meal-v3',s);render(p)};v.querySelector('#padd').onclick=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});const item=v.querySelector('#pitem').value.trim();if(item)s.pantry.push({item,qty:v.querySelector('#pqty').value.trim()});write('elif-os-meal-v3',s);render(p)};v.querySelector('#sadd').onclick=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});const item=v.querySelector('#sitem').value.trim();if(item)s.shopping.push({item,done:false});write('elif-os-meal-v3',s);render(p)};v.querySelectorAll('[data-mdel]').forEach(b=>b.onclick=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});s.plans.splice(+b.dataset.mdel,1);write('elif-os-meal-v3',s);render(p)});v.querySelectorAll('[data-pdel]').forEach(b=>b.onclick=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});s.pantry.splice(+b.dataset.pdel,1);write('elif-os-meal-v3',s);render(p)});v.querySelectorAll('[data-sdel]').forEach(b=>b.onclick=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});s.shopping.splice(+b.dataset.sdel,1);write('elif-os-meal-v3',s);render(p)});v.querySelectorAll('[data-sdone]').forEach(b=>b.onchange=()=>{const s=read('elif-os-meal-v3',{plans:[],pantry:[],shopping:[]});s.shopping[+b.dataset.sdone].done=b.checked;write('elif-os-meal-v3',s)})}
if(p==='glow'){v.querySelectorAll('[data-g]').forEach(b=>b.onchange=()=>{const s=read('elif-os-glow-v2',{days:{}});s.days[day()]??={};s.days[day()][b.dataset.g]=b.checked;write('elif-os-glow-v2',s)});v.querySelector('#gsave').onclick=()=>{const s=read('elif-os-glow-v2',{days:{}});s.days[day()]??={};s.days[day()].note=v.querySelector('#gnote').value;write('elif-os-glow-v2',s)} }
if(p==='wallet'){v.querySelector('#wadd').onclick=()=>{const s=read('elif-os-wallet-v2',{trades:[]});s.trades.unshift({asset:v.querySelector('#wa').value.trim(),pl:Number(v.querySelector('#wpl').value||0),setup:v.querySelector('#wsetup').value,lesson:v.querySelector('#wlesson').value,date:day()});write('elif-os-wallet-v2',s);render(p)};v.querySelectorAll('[data-wdel]').forEach(b=>b.onclick=()=>{const s=read('elif-os-wallet-v2',{trades:[]});s.trades.splice(+b.dataset.wdel,1);write('elif-os-wallet-v2',s);render(p)})}
if(p==='habits'){v.querySelectorAll('[data-h]').forEach(b=>b.onchange=()=>{const s=read('elif-os-habits-v2',{items:['Study','Movement','Water','Sleep','Read','Korean'],log:{}});s.log[day()]??={};s.log[day()][b.dataset.h]=b.checked;write('elif-os-habits-v2',s)})}
if(p==='body'){v.querySelector('#bsave').onclick=()=>{const s=read('elif-os-body-v1',{days:{}});s.days[day()]={weight:v.querySelector('#bw').value,workout:v.querySelector('#bm').value,sleep:v.querySelector('#bs').value,water:v.querySelector('#bwa').value};write('elif-os-body-v1',s);alert('Bugünün verileri kaydedildi.')}}
if(p==='goals'){v.querySelector('#gadd').onclick=()=>{const s=read('elif-os-goals-v2',{items:[]});s.items.push({title:v.querySelector('#gt').value.trim(),area:v.querySelector('#ga').value.trim(),progress:0});write('elif-os-goals-v2',s);render(p)};v.querySelectorAll('[data-gp]').forEach(b=>b.oninput=()=>{const s=read('elif-os-goals-v2',{items:[]});s.items[+b.dataset.gp].progress=Number(b.value);write('elif-os-goals-v2',s);b.nextElementSibling.textContent=b.value+'%' });v.querySelectorAll('[data-gdel]').forEach(b=>b.onclick=()=>{const s=read('elif-os-goals-v2',{items:[]});s.items.splice(+b.dataset.gdel,1);write('elif-os-goals-v2',s);render(p)})}
if(p==='projects'){v.querySelector('#paddproj').onclick=()=>{const s=read('elif-os-projects-v2',{items:[]});s.items.push({name:v.querySelector('#pt').value.trim(),area:v.querySelector('#pa').value.trim(),status:'active'});write('elif-os-projects-v2',s);render(p)};v.querySelectorAll('[data-pdelproj]').forEach(b=>b.onclick=()=>{const s=read('elif-os-projects-v2',{items:[]});s.items.splice(+b.dataset.pdelproj,1);write('elif-os-projects-v2',s);render(p)})}
if(p==='calendar'){let cursor=new Date();const draw=()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),s=read('elif-os-calendar-v2',{events:[]}),grid=v.querySelector('#calgrid');v.querySelector('#cmonth').textContent=cursor.toLocaleDateString('en',{month:'long',year:'numeric'});let h=['M','T','W','T','F','S','S'].map(x=>`<b>${x}</b>`).join('');for(let i=0;i<(first.getDay()+6)%7;i++)h+='<span></span>';for(let n=1;n<=last.getDate();n++){const k=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;h+=`<button class="${k===day()?'today':''}" data-cdate="${k}">${n}</button>`}grid.innerHTML=h;v.querySelector('#events').innerHTML=s.events.slice().reverse().map((x,i)=>`<div class="check"><span class="grow"><b>${esc(x.title)}</b><br><small>${esc(x.date)}</small></span><button class="ghost" data-evdel="${i}">×</button></div>`).join('');v.querySelectorAll('[data-evdel]').forEach(b=>b.onclick=()=>{const ss=read('elif-os-calendar-v2',{events:[]});ss.events.splice(ss.events.length-1-Number(b.dataset.evdel),1);write('elif-os-calendar-v2',ss);draw()})};v.querySelector('#cprev').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);draw()};v.querySelector('#cnext').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);draw()};v.querySelector('#cadd').onclick=()=>{const s=read('elif-os-calendar-v2',{events:[]});const title=v.querySelector('#cevent').value.trim();if(title)s.events.push({title,date:v.querySelector('#cedate').value});write('elif-os-calendar-v2',s);draw()};draw()}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;const p=b.dataset.page;if(!pages[p])return;e.preventDefault();e.stopImmediatePropagation();render(p)},true);
})();
