(()=>{try{
const cards=[
['sleep','sleep.jpeg','Sleep','Rest today for a stronger tomorrow.','☾'],
['study','study.jpeg','Study','Small steps make big results.','▤'],
['body','body.jpeg','Body','Discipline in motion.','♧'],
['glow','glow up.jpeg','Glow Up','A better me, every day.','✧'],
['wallet','walleti.jpeg','Wallet','Financial peace is power.','▤'],
['meal','meal.jpeg','Meal','Nourish to do more.','♜'],
['journal','journal.jpeg','Journal','A clearer mind, a calmer you.','▱'],
['goals','goals.jpeg','Goals','Patience today. A different tomorrow.','◎'],
['projects','projects.jpeg','Projects','Ideas into reality.','□'],
['habits','hobbies.jpeg','Habits','Consistency changes everything.','◌']
];
function addCss(){if(document.getElementById('joshi-dashboard-css'))return;const s=document.createElement('style');s.id='joshi-dashboard-css';s.textContent='.joshi-dashboard{padding:8px 0 30px}.jd-head{display:flex;justify-content:space-between;align-items:end;gap:20px;padding:10px 2px 18px}.jd-title{font:30px Georgia,serif;color:#f1e5ea;letter-spacing:.03em}.jd-sub{font:9px "DM Mono",monospace;letter-spacing:.28em;color:#9f8a96;margin-top:7px}.jd-quote{font:italic 13px Georgia,serif;color:#cdb9c4}.jd-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.jd-card{position:relative;display:block;width:100%;min-height:286px;padding:0;overflow:hidden;border:1px solid #493440;border-radius:14px;background:#100d12;text-align:left;color:inherit;cursor:pointer;box-shadow:0 10px 28px rgba(0,0,0,.16)}.jd-card img{display:block;width:100%;height:188px;object-fit:cover;filter:saturate(.84) contrast(1.04)}.jd-card:after{content:"";position:absolute;left:0;right:0;top:118px;height:100px;background:linear-gradient(transparent,#100d12)}.jd-copy{position:relative;z-index:2;padding:0 14px 14px;margin-top:-3px}.jd-icon{font-size:19px;color:#eadde3}.jd-copy h3{font:20px Georgia,serif;margin:4px 0 3px;color:#f0e4e9}.jd-copy p{font:italic 11px Georgia,serif;line-height:1.35;color:#b9a7b1;margin:0 0 10px}.jd-copy small{font:9px "DM Mono",monospace;letter-spacing:.22em;color:#a887a0}.jd-card[data-page="goals"] img{object-position:center}.jd-card[data-page="wallet"] img{object-position:center}.jd-card[data-page="projects"] img{object-position:center}.jd-card[data-page="journal"] img{object-position:center}.jd-banner{grid-column:1/-1;min-height:150px;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:22px 30px;border:1px solid #493440;border-radius:14px;overflow:hidden;position:relative;background-image:url("banner.png");background-size:cover;background-position:center;background-repeat:no-repeat}.jd-banner:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(15,11,15,.9),rgba(15,11,15,.25),rgba(15,11,15,.82));pointer-events:none}.jd-banner blockquote,.jd-banner .jd-jp{position:relative;z-index:2}.jd-banner blockquote{font:italic 20px Georgia,serif;color:#dfccd5;margin:0}.jd-banner blockquote small,.jd-jp small{display:block;margin-top:8px;font:9px "DM Mono",monospace;letter-spacing:.28em;color:#a98f9c}.jd-jp{text-align:right;font:16px Georgia,serif;color:#d9c7cf}.jd-jp small{margin-top:6px}.module-hero{display:none!important}@media(max-width:1100px){.jd-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){.jd-head{align-items:flex-start;flex-direction:column}.jd-grid{grid-template-columns:1fr 1fr}.jd-card{min-height:250px}.jd-card img{height:160px}.jd-banner{grid-column:1/-1;align-items:flex-start;flex-direction:column}.jd-jp{text-align:left}}@media(max-width:470px){.jd-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function renderHome(){const v=document.querySelector('#view');if(!v||v.dataset.page!=='home')return;v.dataset.jd='1';const html=cards.map(c=>'<button type="button" class="jd-card" data-page="'+c[0]+'"><img src="'+c[1]+'" alt="'+c[2]+'"><div class="jd-copy"><div class="jd-icon">'+c[4]+'</div><h3>'+c[2]+'</h3><p>'+c[3]+'</p><small>MODULE / '+c[2].toUpperCase()+'</small></div></button>').join('');v.innerHTML='<section class="joshi-dashboard"><div class="jd-head"><div><div class="jd-title">JOSHI OS //</div><div class="jd-sub">DISCIPLINE CREATES FREEDOM.</div></div><div class="jd-quote">“A better me, a kinder world.”</div></div><div class="jd-grid">'+html+'<div class="jd-banner"><blockquote>“These fools could never make me sweat.”<small>OBITO</small></blockquote><div class="jd-jp">いつか、きっと。<small>SOMEDAY, FOR SURE.</small></div></div></div></section>'}
function tick(){addCss();const v=document.querySelector('#view');if(v&&v.dataset.page==='home')renderHome()}
tick();const root=document.getElementById('view');if(root)new MutationObserver(()=>requestAnimationFrame(tick)).observe(root,{attributes:true,childList:true,subtree:false});window.addEventListener('click',e=>{if(e.target.closest&&e.target.closest('button[data-page]'))setTimeout(tick,0)});
}catch(e){console.warn('JOSHI dashboard polish disabled',e)}})();