(()=>{
const KEY='elif-os-v2-state', esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const core=()=>window.ELIFCore;
const today=()=>core()?.today?core().today():(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})();
const read=()=>core()?.read?.()||JSON.parse(localStorage.getItem(KEY)||'{}');
const write=s=>core()?.write?.(s)||localStorage.setItem(KEY,JSON.stringify(s));
const uid=()=>crypto.randomUUID();
const active=x=>(x?.status||'active')==='active';
const fmt=d=>{if(!d)return 'No date';if(d===today())return 'Today';const a=d.split('-').map(Number),x=new Date(a[0],a[1]-1,a[2]);return x.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})};
const modal=(title,body)=>{const m=document.querySelector('#modal');if(!m)return;m.innerHTML=`<div class="modalbox task-modal"><button class="close" data-te-close>×</button><span class="eyebrow">TASK ENGINE</span><h2>${title}</h2>${body}</div>`;m.classList.add('open')};
const options=(arr,id,label,empty='— none —')=>`<label class="field">${label}<select name="${id}"><option value="">${empty}</option>${arr.filter(active).map(x=>`<option value="${x.id}">${esc(x.title||x.name)}</option>`).join('')}</select></label>`;
function form(task){const s=read(),projects=s.projects||[],goals=s.goals||[];return `<form data-task-engine-form data-id="${task?.id||''}"><label class="field">Task title<input name="title" value="${esc(task?.title||'')}" required autofocus></label><div class="te-grid"><label class="field">Due date<input name="date" type="date" value="${esc(task?.date||today())}" required></label><label class="field">Priority<select name="priority"><option value="low" ${task?.priority==='low'?'selected':''}>Low</option><option value="medium" ${!task||task?.priority==='medium'?'selected':''}>Medium</option><option value="high" ${task?.priority==='high'?'selected':''}>High</option></select></label></div>${options(projects,'projectId','Project')}${options(goals,'goalId','Goal')}<label class="field">Notes<textarea name="notes" placeholder="Optional context...">${esc(task?.notes||'')}</textarea></label><div class="actions"><button type="button" class="ghost" data-te-close>cancel</button><button class="primary">${task?'update':'create task'}</button></div></form>`}
function openNew(){modal('New task',form(null))}
function openEdit(id){const s=read(),t=(s.tasks||[]).find(x=>x.id===id);if(t)modal('Edit task',form(t))}
function render(){if(document.querySelector('#view')?.dataset.page!=='tasks')return;const host=document.querySelector('#view .data');if(!host||host.querySelector('.task-engine'))return;const s=read(),tasks=(s.tasks||[]).filter(active),t=today(),overdue=tasks.filter(x=>!x.done&&x.date&&x.date<t).length,done=tasks.filter(x=>x.done).length,open=tasks.length-done;host.innerHTML=`<div class="panel task-engine"><div class="te-summary"><div><span class="eyebrow">TASK ENGINE</span><h2>Execution queue</h2><p>${open} open · ${done} completed · ${overdue} overdue</p></div><button class="primary" data-te-new>＋ new task</button></div><div class="te-filters"><input id="te-search" placeholder="Search tasks..." aria-label="Search tasks"><select id="te-filter"><option value="all">All tasks</option><option value="today">Today</option><option value="overdue">Overdue</option><option value="open">Open</option><option value="completed">Completed</option><option value="high">High priority</option></select><select id="te-sort"><option value="date">Due date</option><option value="priority">Priority</option><option value="created">Newest</option></select></div><div id="te-list"></div></div>`;paint();}
function paint(){const s=read(),box=document.querySelector('#te-list');if(!box)return;let tasks=(s.tasks||[]).filter(active),q=(document.querySelector('#te-search')?.value||'').trim().toLowerCase(),filter=document.querySelector('#te-filter')?.value||'all',sort=document.querySelector('#te-sort')?.value||'date',t=today();tasks=tasks.filter(x=>{const text=`${x.title} ${x.priority} ${x.notes||''}`.toLowerCase();if(q&&!text.includes(q))return false;if(filter==='today'&&x.date!==t)return false;if(filter==='overdue'&&!(x.date&&x.date<t&&!x.done))return false;if(filter==='open'&&x.done)return false;if(filter==='completed'&&!x.done)return false;if(filter==='high'&&x.priority!=='high')return false;return true});const rank={high:0,medium:1,low:2};tasks.sort((a,b)=>sort==='priority'?rank[a.priority]-rank[b.priority]:sort==='created'?String(b.createdAt||'').localeCompare(String(a.createdAt||'')):String(a.date||'9999').localeCompare(String(b.date||'9999')));box.innerHTML=tasks.length?tasks.map(taskRow).join(''):`<div class="te-empty"><b>No tasks in this view.</b><span>Try another filter or create a task.</span></div>`;}
function taskRow(x){const t=today(),over=!x.done&&x.date&&x.date<t,s=read(),p=(s.projects||[]).find(y=>y.id===x.projectId),g=(s.goals||[]).find(y=>y.id===x.goalId);return `<article class="te-task ${x.done?'is-done':''} ${over?'is-overdue':''}" data-te-row="${x.id}"><button class="te-check ${x.done?'checked':''}" data-te-toggle="${x.id}" aria-label="${x.done?'Mark open':'Complete task'}">${x.done?'✓':''}</button><div class="te-main"><div class="te-title">${esc(x.title)}</div><div class="te-meta"><span class="te-priority ${x.priority||'medium'}">${x.priority||'medium'}</span><span>${fmt(x.date)}</span>${over?'<b class="te-overdue">OVERDUE</b>':''}${p?`<span>↳ ${esc(p.name)}</span>`:''}${g?`<span>◎ ${esc(g.title)}</span>`:''}</div>${x.notes?`<div class="te-notes">${esc(x.notes)}</div>`:''}</div><div class="te-actions"><button data-te-edit="${x.id}" aria-label="Edit task">edit</button><button data-te-delete="${x.id}" aria-label="Delete task">delete</button></div></article>`}
function saveTask(f){const s=read();s.tasks??=[];const x=new FormData(f),id=f.dataset.id,title=String(x.get('title')||'').trim();if(!title)return;const data={title,date:x.get('date')||today(),priority:x.get('priority')||'medium',projectId:x.get('projectId')||null,goalId:x.get('goalId')||null,notes:String(x.get('notes')||'').trim()};if(id){const task=s.tasks.find(a=>a.id===id);if(!task)return;Object.assign(task,data)}else s.tasks.push({id:uid(),...data,done:false,status:'active',createdAt:new Date().toISOString()});write(s);location.reload()}
document.addEventListener('click',e=>{if(document.querySelector('#view')?.dataset.page!=='tasks')return;const b=e.target.closest('button');if(!b)return;if(b.matches('[data-te-new]')){e.preventDefault();e.stopImmediatePropagation();openNew()}else if(b.dataset.teEdit){e.preventDefault();e.stopImmediatePropagation();openEdit(b.dataset.teEdit)}else if(b.dataset.teDelete){e.preventDefault();e.stopImmediatePropagation();const s=read(),i=(s.tasks||[]).findIndex(x=>x.id===b.dataset.teDelete);if(i>=0&&confirm('Delete this task?')){s.tasks.splice(i,1);write(s);location.reload()}}else if(b.dataset.teToggle){e.preventDefault();e.stopImmediatePropagation();const s=read(),task=(s.tasks||[]).find(x=>x.id===b.dataset.teToggle);if(task){task.done=!task.done;task.completedAt=task.done?new Date().toISOString():null;write(s);location.reload()}}else if(b.matches('[data-te-close]')){e.preventDefault();e.stopImmediatePropagation();document.querySelector('#modal')?.classList.remove('open')}},true);
document.addEventListener('submit',e=>{const f=e.target.closest('form[data-task-engine-form]');if(!f)return;e.preventDefault();e.stopImmediatePropagation();saveTask(f)},true);
document.addEventListener('input',e=>{if(e.target.id==='te-search')paint()});document.addEventListener('change',e=>{if(e.target.id==='te-filter'||e.target.id==='te-sort')paint()});
const obs=new MutationObserver(()=>{if(document.querySelector('#view')?.dataset.page==='tasks'&&!document.querySelector('#view .data .task-engine'))render()});obs.observe(document.body,{childList:true,subtree:true});setTimeout(render,0);
})();